/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.houndkirk.weather.parser;

import com.github.houndkirk.weather.parser.utils.TestUtils;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Paths;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.notNullValue;
import static org.hamcrest.Matchers.nullValue;

class WeatherSpreadsheetParserTest {

    public static final String SPREADSHEET_FILE_NAME = "build/resources/test/weather.ods";

    private static final int YEAR = TestUtils.YEAR;

    private WeatherSpreadsheetParser spreadsheetParser;

    @BeforeEach
    void setUp() {
        spreadsheetParser = new WeatherSpreadsheetParser();
    }

    @Test
    void canParseSpreadsheetFromFile() {
        WeatherSpreadsheet spreadsheet = spreadsheetParser.parse(SPREADSHEET_FILE_NAME);
        assertThat(spreadsheet, notNullValue());
    }

    @Test
    void canParseSpreadsheetFromStream() throws IOException {
        InputStream stream = new BufferedInputStream(Files.newInputStream(Paths.get("build/resources/test/weather.ods")));
        WeatherSpreadsheet spreadsheet = spreadsheetParser.parse(stream);
        assertThat(spreadsheet, notNullValue());
    }

    @Test
    void parseNonExistentFileFails() {
        WeatherSpreadsheet spreadsheet = spreadsheetParser.parse("file_does_not_exist");
        assertThat(spreadsheet, nullValue());
    }
}
